# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Intelliclima CH
version: "0.1.0"
slug: Intelliclimach
description: Intelliclimach app
url: "https://github.com/smtpserver/intelliclimach/custom_components/intelliclimach"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Inteliclima CH ..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/app-example"